# LEARN ML

## Session 1: Intro to Python and Numpy

### Breif History 

- Released in 1991
- good on different platforms 
- **simple** syntax
- no usage of semi-colons, **new lines** are used to complete a command
- in most programming langugaes curly brackets {...} are used to define scope,
  however in Python indents and whitespace is used
     - this is **very important** indentation in Python has a **meaning** and 
       is not only used for readability
- comments in Python are denoted by #

##   Data Types

There are 4 primative data types in Python:
    1. Intergers
    2. Booleans 
    3. Floats 
    4. Strings

### You can check the type of anything using the  type() function

For example:

In [2]:
type("Hello World!")

str

Notice we did not use ; at the end 

In [3]:
type(True)

bool

### Type Casting:

You can cast from one type to another using int(), str(), float() and bool()

For example:

In [9]:
int(12.67)
# notice that the number has been rounded down NOT up

12

In [10]:
str(12.33)

'12.33'

In [13]:
bool(2==3) # 2 and 3 are not equal, therefore false 

False

In [14]:
bool(2==2)

True

In [15]:
bool(None) #bool() returns false when None type is an input

False

In [16]:
bool({}) #bool() returns false when an empty mapping is an input

False

## Variables

Unlike some other programming languages, you don't have to declare variables in Python

Naming Conventions:
    - name of variable can't start with a number
    - can't contain a space 

In [17]:
num_flowers= 60

In [18]:
type(num_flowers) #without declartion Python knows type of variable 

int

In [19]:
greeting= "Hello World!"

In [20]:
type(greeting)

str

##  If Statments

Similar to most programming languages

In [23]:
num_flowers= 5
if num_flowers <6:
    # note the ':'' after the if statment 
    print("Very few flowers!") 

Very few flowers!


In [26]:
num_flowers= 5
if num_flowers <6:
    
print("Very few flowers!")
#notice that the indent is NEEDED, otherwise error

IndentationError: expected an indented block (<ipython-input-26-c59eaed49448>, line 4)

If- Else statments follow similar logic

In [29]:
num_cakes=2
if num_cakes <5:
    print('we need more cakes!')
else:
    print('Too many cakes')

we need more cakes!


## Lists

Lists in Python are ordered sequences <br> indexing starts at **0** <br> access items using **[ ]** <br> adding items to a list can be done by **append()** and **insert()**

In [52]:
subjects = ["math","science","art","historty"]

In [53]:
type(subjects)

list

In [54]:
subjects[0] #acessing an index

'math'

In [55]:
type(subjects[0])

str

In [56]:
subjects[0]= "gym" #reassignment

In [57]:
print(subjects)

['gym', 'science', 'art', 'historty']


In [58]:
subjects.append("math") #goes to last index

In [59]:
print(subjects)

['gym', 'science', 'art', 'historty', 'math']


In [60]:
subjects.insert(2,"english") #use insert, to insert in a defined location

In [61]:
print(subjects)

['gym', 'science', 'english', 'art', 'historty', 'math']


In [62]:
len(subjects) #length of subject

6

In [64]:
subjects.extend(["geography","Music","French"]) 
#add a new list to original

In [65]:
print(subjects)

['gym', 'science', 'english', 'art', 'historty', 'math', 'geography', 'Music', 'French']


In [68]:
del(subjects[0])

In [69]:
print(subjects)

['science', 'english', 'art', 'historty', 'math', 'geography', 'Music', 'French']


### .split()

Is used to split a string and convert it into an list <br> splits where there is a new space

In [70]:
speech= "I am very happy today. I got some free food"

In [71]:
speech_list=speech.split()

In [72]:
type(speech_list)

list

In [73]:
print(speech_list)

['I', 'am', 'very', 'happy', 'today.', 'I', 'got', 'some', 'free', 'food']


In [80]:
speech_sen=speech.split('.') #pass an argument to split at a given character

In [81]:
print(speech_sen)

['I am very happy today', ' I got some free food']


In [82]:
len(speech_sen)

2

### Range of Indexs

In [85]:
word="my amazing list, it is so cool"

In [86]:
word_split=word.split()

In [88]:
print(word_split[2:5]) #will print from the 2nd index to the 4th

['list,', 'it', 'is']


In [90]:
print(word_split[:2]) #will print until the 2nd index

['my', 'amazing']


In [92]:
print(word_split[2:]) #will print from the 2nd index onward

['list,', 'it', 'is', 'so', 'cool']


## Tuples

Unlike lists you **CAN'T** change a tuple once its been created

In [93]:
tuple1= ("boat","hat","car")

In [94]:
type(tuple1)

tuple

In [96]:
print(tuple1)

('boat', 'hat', 'car')


You can't change vlaues in a tuple, however you can convert the tuple to a list, change the value and convert back to a tuple

In [97]:
list_t=list(tuple1)

In [98]:
list_t

['boat', 'hat', 'car']

In [99]:
list_t[1]="house"

In [100]:
tuple1=tuple(list_t)

In [101]:
tuple1

('boat', 'house', 'car')

## Dictionaries

Have keys and values <br> keys are like index, but not necessarily numbers

In [102]:
my_dictonary={"colour":"red","size":7,"company":"Nike"}

In [103]:
type(my_dictonary)

dict

In [104]:
print(my_dictonary)

{'colour': 'red', 'size': 7, 'company': 'Nike'}


In [105]:
my_dictonary["colour"] #in this sense you get to choose the index

'red'

In [106]:
len(my_dictonary) #how many key-value pairs there are

3

In [110]:
my_dictonary.keys()# returns all keys in dictonary

dict_keys(['colour', 'size', 'company'])

In [111]:
my_dictonary.values() #returns all values

dict_values(['red', 7, 'Nike'])

##  For Loops

- used for iterating over a sequence 

In [112]:
names=["bob","sandy","pam"]
for x in names:
    #note the ':'
    print(x)
    #note the indentation!

bob
sandy
pam


## Numpy

- Python library for scientific computing
- provides n-dimensional array objects 

In [113]:
import numpy as np #import the libaray

In [114]:
list1=[0,1,2,3,4]

In [115]:
arr1=np.array(list1) 

In [116]:
type(arr1) 

numpy.ndarray

These arrays are desgined to handle vectorized operations

In [117]:
list1+2 #gives an error 

TypeError: can only concatenate list (not "int") to list

In [118]:
arr1+2 #each element has 2 added to it

array([2, 3, 4, 5, 6])

In [120]:
#2D array
list2=[[1,2,3],[4,5,6],[7,8,90]]
arr2=np.array(list2,dtype='float') 
#using the dtype argument, we can specify which type the array elements are

In [121]:
arr2

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8., 90.]])

In [122]:
arr2.shape #how many items are present in each dimension

(3, 3)

In [123]:
arr2.dtype #the type of the elements

dtype('float64')

In [124]:
arr2.size #total number of elements

9

We can also apply a boolean output to the whole array

In [125]:
b=arr2>3

In [127]:
b #shows true where condition is true

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

You can easily compute the mean,max and min for an array using built-in functions

In [129]:
print(arr2.mean())
print(arr2.max())
print(arr2.min())

14.0
90.0
1.0


if you only want to compute the min for only the rows or cols use amin

In [131]:
print(np.amin(arr2,axis=0)) #cols
print(np.amin(arr2,axis=1)) #rows

[1. 2. 3.]
[1. 4. 7.]


In [132]:
print(np.amax(arr2,axis=0)) #cols
print(np.amax(arr2,axis=1)) #rows

[ 7.  8. 90.]
[ 3.  6. 90.]


### Reshaping arrays

Lets say we want to turn a 4x3 array into a 3x4 array

In [135]:
my_list=([1,2,3],[4,5,6,],[7,8,9],[10,11,12])

In [136]:
my_arr=np.array(my_list)

In [138]:
my_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [139]:
my_arr.shape

(4, 3)

### Change shape using reshape() function

In [142]:
my_arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### To flatten an array (change to 1x1 array) use flatten() function

In [147]:
my_arr_flat= my_arr.flatten()

In [148]:
my_arr_flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [149]:
my_arr_flat[2]=90

In [150]:
my_arr_flat

array([ 1,  2, 90,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [152]:
my_arr #chaning my_arr_flat does not change the original array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### We can use another function called  ravel() , when using this function the parent array is effected if the child is modified. The modifications in the child are reflected in the parent

In [153]:
my_arr_ravel=my_arr.ravel()

In [154]:
my_arr_ravel

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [155]:
my_arr_ravel[2]=90

In [156]:
my_arr_ravel

array([ 1,  2, 90,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [157]:
my_arr #we see the the change in the parent as well

array([[ 1,  2, 90],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### Numpy has many built-in functions which are useful

In [159]:
np.arange(5) #creates a sequence from 0-4 in the form of an array

array([0, 1, 2, 3, 4])

In [160]:
np.arange(0,10,2) #start at 0 to 9, with a step of 2

array([0, 2, 4, 6, 8])

In [164]:
np.arange(10,0,-2) #negative sign indicates descending order

array([10,  8,  6,  4,  2])

Lets say you want to create an array of 10 numbers between  1 and 75, incrementing at the same amount each time 

Calculating the step value would be difficult and would take time, so we use the <span style= "color: green"> linspace() </span> function

In [168]:
np.linspace(1,75,10) 

array([ 1.        ,  9.22222222, 17.44444444, 25.66666667, 33.88888889,
       42.11111111, 50.33333333, 58.55555556, 66.77777778, 75.        ])

In [171]:
np.linspace(1,75,10,dtype=int) 
#force integer values, but step not consistent 

array([ 1,  9, 17, 25, 33, 42, 50, 58, 66, 75])

 ### Counting unique items in an array

In [178]:
arr3=np.random.randint(0,20,size=10)
arr3
#create a 2x2 array of random integers from 0-20

array([12, 12,  6,  2,  3,  2,  7,  2, 13,  0])

In [181]:
uniques,counts=np.unique(arr3,return_counts=True)
#this will return 2 values, which will be assigned to the 2 varaibles
print(uniques)
print(counts)

[ 0  2  3  6  7 12 13]
[1 3 1 1 1 2 1]
